-- PostgreSQL baseline. Application role should not own these tables.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS tenants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), display_name text NOT NULL, status text NOT NULL DEFAULT 'ACTIVE', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), name text NOT NULL, owner_user_id text NOT NULL, version text NOT NULL, environment text NOT NULL, status text NOT NULL, risk_tier text NOT NULL DEFAULT 'STANDARD', contract jsonb, contract_hash text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS actions_catalog(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), code text NOT NULL, integration_id text NOT NULL, operation_type text NOT NULL, data_classification text NOT NULL, base_risk int NOT NULL DEFAULT 0 CHECK(base_risk BETWEEN 0 AND 100), reversible boolean NOT NULL DEFAULT false, UNIQUE(tenant_id,code));
CREATE TABLE IF NOT EXISTS policies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), name text NOT NULL, version int NOT NULL, priority int NOT NULL DEFAULT 0, status text NOT NULL, rules jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS action_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), request_id uuid NOT NULL, trace_id uuid NOT NULL, agent_id uuid NOT NULL REFERENCES agents(id), action_id uuid NOT NULL REFERENCES actions_catalog(id), payload_hash text NOT NULL, contract_hash text, input_context jsonb, runtime_context jsonb, payload_encrypted bytea, decision text NOT NULL, risk jsonb NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,request_id));
CREATE TABLE IF NOT EXISTS approval_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), action_request_id uuid NOT NULL REFERENCES action_requests(id), payload_hash text NOT NULL, required_approvals int NOT NULL CHECK(required_approvals>0), status text NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS approvals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), approval_request_id uuid NOT NULL REFERENCES approval_requests(id), approver_user_id text NOT NULL, decision text NOT NULL, justification text NOT NULL, step_up_verified boolean NOT NULL DEFAULT false, decided_at timestamptz NOT NULL DEFAULT now(), UNIQUE(approval_request_id,approver_user_id));
CREATE TABLE IF NOT EXISTS kill_switches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), scope_type text NOT NULL, scope_id text NOT NULL, reason text NOT NULL, status text NOT NULL, activated_by text NOT NULL, activated_at timestamptz NOT NULL DEFAULT now(), deactivated_at timestamptz);
CREATE TABLE IF NOT EXISTS audit_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), sequence_number bigint NOT NULL, request_id uuid, trace_id uuid, event_type text NOT NULL, actor_type text NOT NULL, actor_id text NOT NULL, agent_id uuid, resource_type text, resource_id text, metadata_redacted jsonb NOT NULL DEFAULT '{}', previous_event_hash text NOT NULL, event_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,sequence_number));
CREATE INDEX IF NOT EXISTS idx_audit_trace ON audit_events(tenant_id,trace_id);
CREATE INDEX IF NOT EXISTS idx_action_agent ON action_requests(tenant_id,agent_id,created_at DESC);
ALTER TABLE agents ENABLE ROW LEVEL SECURITY; ALTER TABLE actions_catalog ENABLE ROW LEVEL SECURITY; ALTER TABLE policies ENABLE ROW LEVEL SECURITY; ALTER TABLE action_requests ENABLE ROW LEVEL SECURITY; ALTER TABLE approval_requests ENABLE ROW LEVEL SECURITY; ALTER TABLE approvals ENABLE ROW LEVEL SECURITY; ALTER TABLE kill_switches ENABLE ROW LEVEL SECURITY; ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
-- The connection pool must SET LOCAL app.tenant_id after verified authentication.
CREATE POLICY tenant_agents ON agents USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
CREATE POLICY tenant_actions ON actions_catalog USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
CREATE POLICY tenant_policies ON policies USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
CREATE POLICY tenant_requests ON action_requests USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
CREATE POLICY tenant_approval_requests ON approval_requests USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
CREATE POLICY tenant_approvals ON approvals USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
CREATE POLICY tenant_kill_switches ON kill_switches USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
CREATE POLICY tenant_audit ON audit_events USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
REVOKE UPDATE, DELETE ON audit_events FROM PUBLIC;

CREATE OR REPLACE FUNCTION prevent_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit_events is append-only'; END; $$;
DROP TRIGGER IF EXISTS trg_audit_append_only ON audit_events;
CREATE TRIGGER trg_audit_append_only BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();
