const STORE_KEY='geAliancaLimaControl.v1';
const APPS=['Mercado Livre','Lalamove','Shopee','Amazon','Loggi','Cliente Direto','Condomínios','Governo','Outros'];
const defaultState={
  settings:{costPerKm:0.65,fixedCosts:2660,monthlyTarget:12800,profitTarget:10000,vehicle:'Fiat Strada 2014 Cabine Estendida',driver:'Glauston Lima'},
  freights:[],tolls:[],receivables:[],fuel:[],cashflow:[],clients:[],maintenance:[],installments:[],agenda:[]
};
let state=loadState();
let current='dashboard';
let deferredPrompt=null;
const $=s=>document.querySelector(s);
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const num=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:2});
const dateBR=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const today=()=>new Date().toISOString().slice(0,10);
function loadState(){try{return {...structuredClone(defaultState),...JSON.parse(localStorage.getItem(STORE_KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state));toast('Salvo');render();}
function toast(msg){const el=$('#toast');el.textContent=msg;el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,2200)}
function sum(arr,fn){return arr.reduce((a,x)=>a+Number(fn(x)||0),0)}
function freightCalc(f){const km=Math.max(Number(f.kmFinal||0)-Number(f.kmInitial||0),Number(f.km||0),0);const base=km*Number(state.settings.costPerKm||0);const total=base+Number(f.toll||0)+Number(f.otherCosts||0);const revenue=Number(f.gross||0);return {km,base,total,result:revenue-total,rpk:km?revenue/km:0,margin:revenue?(revenue-total)/revenue:0};}
function receivableCalc(r){const predicted=Number(r.gross||0)-Number(r.fees||0);const received=Number(r.received||0);const due=r.dueDate?Math.max(Math.floor((new Date(today())-new Date(r.dueDate))/86400000),0):0;return {predicted,diff:r.status==='Recebido'?received-predicted:0,days:['Recebido','Cancelado'].includes(r.status)?0:due};}
function fuelCalc(item,index){const prev=state.fuel.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||''))[index-1];const total=Number(item.liters||0)*Number(item.pricePerLiter||0);const km=prev&&item.odometer&&prev.odometer?Math.max(Number(item.odometer)-Number(prev.odometer),0):Number(item.km||0);return {total,km,kml:Number(item.liters)?km/Number(item.liters):0,costKm:km?total/km:0};}
const nav=[['dashboard','▦','Dashboard'],['freights','🚚','Fretes'],['tolls','🛣️','Pedágios'],['receivables','💰','Recebíveis'],['fuel','⛽','Combustível'],['cashflow','↔','Fluxo de Caixa'],['clients','👥','Clientes'],['maintenance','🔧','Manutenção'],['installments','🚘','Strada / Parcelas'],['agenda','📅','Agenda'],['settings','⚙️','Configurações']];
function buildNav(){const n=$('#nav');n.innerHTML=nav.map(([id,ico,label])=>`<button class="nav-btn ${current===id?'active':''}" data-page="${id}"><span class="ico">${ico}</span>${label}</button>`).join('');n.querySelectorAll('button').forEach(b=>b.onclick=()=>{current=b.dataset.page;$('#sidebar').classList.remove('open');render()})}
function render(){buildNav();const label=nav.find(x=>x[0]===current)?.[2]||'';$('#pageTitle').textContent=label;const c=$('#content');c.innerHTML=pages[current]();bindPage();}
function kpi(label,value,sub=''){return `<div class="card kpi"><div class="label">${label}</div><div class="value">${value}</div><div class="sub">${sub}</div></div>`}
function empty(msg){return `<div class="empty">${msg}</div>`}
function sectionHead(title,sub,action=''){return `<div class="section-head"><div><h2>${title}</h2><p>${sub}</p></div>${action}</div>`}
function actionsButton(label,action,cls=''){return `<button class="btn ${cls}" data-action="${action}">${label}</button>`}
const pages={
 dashboard(){
   const totalRevenue=sum(state.freights,f=>f.gross), km=sum(state.freights,f=>freightCalc(f).km), costs=sum(state.freights,f=>freightCalc(f).total), result=totalRevenue-costs;
   const toReceive=sum(state.receivables,r=>['Recebido','Cancelado'].includes(r.status)?0:receivableCalc(r).predicted);
   const received=sum(state.receivables,r=>r.status==='Recebido'?Number(r.received||receivableCalc(r).predicted):0);
   const tolls=sum(state.tolls,t=>Math.max(Number(t.value||0)-Number(t.reimbursed||0),0));
   const fuel=sum(state.fuel,(f,i)=>fuelCalc(f,i).total);
   const byApp={}; state.freights.forEach(f=>byApp[f.app]=(byApp[f.app]||0)+Number(f.gross||0));const max=Math.max(...Object.values(byApp),1);
   return `${sectionHead('Visão executiva','Resultado da operação, recebíveis e eficiência','<div class="actions">'+actionsButton('+ Novo frete','addFreight')+actionsButton('Novo recebível','addReceivable','secondary')+'</div>')}
   <div class="grid kpis">${kpi('Receita Bruta',money(totalRevenue),`${state.freights.length} frete(s)`)}${kpi('Resultado Estimado',money(result),`Margem ${totalRevenue?num(result/totalRevenue*100):0}%`)}${kpi('A Receber',money(toReceive),`Recebido ${money(received)}`)}${kpi('Km Rodados',num(km),`Receita/km ${money(km?totalRevenue/km:0)}`)}</div>
   <div class="grid two" style="margin-top:16px"><div class="card"><strong>Resultado por origem</strong><div class="bar-list" style="margin-top:16px">${Object.keys(byApp).length?Object.entries(byApp).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="bar-row"><span>${k||'Outros'}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(v/max*100,3)}%"></div></div><strong>${money(v)}</strong></div>`).join(''):empty('Registre o primeiro frete para visualizar.')}</div></div>
   <div class="card"><strong>Custos e metas</strong><div class="summary-list" style="margin-top:14px"><div class="summary-item"><span>Custo/km parametrizado</span><strong>${money(state.settings.costPerKm)}</strong></div><div class="summary-item"><span>Pedágio líquido</span><strong>${money(tolls)}</strong></div><div class="summary-item"><span>Combustível registrado</span><strong>${money(fuel)}</strong></div><div class="summary-item"><span>Meta mensal</span><strong>${money(state.settings.monthlyTarget)}</strong></div><div class="summary-item"><span>Atingimento da meta</span><strong>${num(state.settings.monthlyTarget?totalRevenue/state.settings.monthlyTarget*100:0)}%</strong></div></div></div></div>
   ${sectionHead('Acesso rápido','Lançamentos mais usados')}
   <div class="quick-grid"><button class="quick" data-action="addFreight"><strong>🚚 Registrar frete</strong><span>Km, receita, pedágio e resultado</span></button><button class="quick" data-action="addFuel"><strong>⛽ Abastecimento</strong><span>Litros, preço e odômetro</span></button><button class="quick" data-action="addToll"><strong>🛣️ Pedágio</strong><span>Praça, trecho e reembolso</span></button><button class="quick" data-action="addReceivable"><strong>💰 Recebível</strong><span>Vencimento e baixa do pagamento</span></button></div>`;
 },
 freights(){return listPage('Fretes','Controle de corridas, receita e custo por km','addFreight',freightTable())},
 tolls(){return listPage('Pedágios','Custos por trecho e reembolsos','addToll',tollTable())},
 receivables(){return listPage('Recebíveis por App / Empresa','Valores previstos, recebidos e atrasos','addReceivable',receivableTable())},
 fuel(){return listPage('Combustível','Consumo, km/l e custo por km','addFuel',fuelTable())},
 cashflow(){return listPage('Fluxo de Caixa','Entradas e saídas financeiras','addCash',cashTable())},
 clients(){return listPage('Clientes','Base comercial e contatos','addClient',clientTable())},
 maintenance(){return listPage('Manutenção','Histórico e próximas revisões','addMaintenance',maintenanceTable())},
 installments(){return listPage('Strada / Parcelas','Compromissos do veículo','addInstallment',installmentTable())},
 agenda(){return listPage('Agenda','Compromissos e tarefas operacionais','addAgenda',agendaTable())},
 settings(){return `${sectionHead('Configurações da Operação','Parâmetros usados nos cálculos')}
 <div class="grid two"><div class="card"><form id="settingsForm" class="form-grid" style="padding:0"><div class="field"><label>Custo operacional por km</label><input name="costPerKm" type="number" step="0.01" value="${state.settings.costPerKm}"></div><div class="field"><label>Custos fixos mensais</label><input name="fixedCosts" type="number" step="0.01" value="${state.settings.fixedCosts}"></div><div class="field"><label>Meta de faturamento mensal</label><input name="monthlyTarget" type="number" step="0.01" value="${state.settings.monthlyTarget}"></div><div class="field"><label>Meta de lucro mensal</label><input name="profitTarget" type="number" step="0.01" value="${state.settings.profitTarget}"></div><div class="field full"><label>Veículo</label><input name="vehicle" value="${state.settings.vehicle}"></div><div class="field full"><label>Motorista padrão</label><input name="driver" value="${state.settings.driver}"></div><div class="form-actions"><button class="btn" type="submit">Salvar parâmetros</button></div></form></div>
 <div class="card"><strong>Backup e portabilidade</strong><p class="muted">Exporte um arquivo JSON para guardar uma cópia completa dos lançamentos ou migrar para outro aparelho.</p><div class="actions" style="margin-top:16px"><button class="btn secondary" data-action="exportData">Exportar backup</button><button class="btn ghost" data-action="importData">Importar backup</button><button class="btn danger" data-action="resetData">Zerar dados</button></div><div class="notice" style="margin-top:18px"><strong>Importante:</strong> esta versão salva os dados no próprio navegador. Para edição simultânea entre celulares, o próximo passo é ligar o app a uma base online com autenticação.</div></div></div>`}
};
function listPage(title,sub,action,table){return `${sectionHead(title,sub,actionsButton('+ Novo registro',action))}<div class="table-wrap">${table}</div>`}
function table(headers,rows,emptyMsg='Nenhum registro ainda.'){return rows.length?`<table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`:empty(emptyMsg)}
function delBtn(type,id){return `<button class="btn small danger" data-delete="${type}:${id}">Excluir</button>`}
function freightTable(){return table(['Data','App/Empresa','ID','Origem → Destino','Km','Bruto','Custo','Resultado','R$/Km','Status',''],state.freights.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(f=>{const c=freightCalc(f);return `<tr><td>${dateBR(f.date)}</td><td>${f.app||'—'}</td><td>${f.ref||'—'}</td><td>${f.origin||'—'} → ${f.destination||'—'}</td><td>${num(c.km)}</td><td>${money(f.gross)}</td><td>${money(c.total)}</td><td class="${c.result>=0?'positive':'negative'}">${money(c.result)}</td><td>${money(c.rpk)}</td><td><span class="pill">${f.status||'Concluído'}</span></td><td>${delBtn('freights',f.id)}</td></tr>`}))}
function tollTable(){return table(['Data','App/Empresa','ID Frete','Praça','Trecho','Pedágio','Reembolsado','Custo Líquido',''],state.tolls.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(t=>{const net=Math.max(Number(t.value||0)-Number(t.reimbursed||0),0);return `<tr><td>${dateBR(t.date)}</td><td>${t.app||'—'}</td><td>${t.ref||'—'}</td><td>${t.plaza||'—'}</td><td>${t.route||'—'}</td><td>${money(t.value)}</td><td>${money(t.reimbursed)}</td><td>${money(net)}</td><td>${delBtn('tolls',t.id)}</td></tr>`}))}
function receivableTable(){return table(['Serviço','Vencimento','App/Empresa','ID','Previsto','Status','Recebido','Diferença','Dias',''],state.receivables.slice().sort((a,b)=>(b.serviceDate||'').localeCompare(a.serviceDate||'')).map(r=>{const c=receivableCalc(r);const pill=r.status==='Recebido'?'':c.days>0?'bad':'warn';return `<tr><td>${dateBR(r.serviceDate)}</td><td>${dateBR(r.dueDate)}</td><td>${r.app||'—'}</td><td>${r.ref||'—'}</td><td>${money(c.predicted)}</td><td><span class="pill ${pill}">${r.status||'Pendente'}</span></td><td>${money(r.received)}</td><td class="${c.diff<0?'negative':'positive'}">${money(c.diff)}</td><td>${c.days}</td><td>${delBtn('receivables',r.id)}</td></tr>`}))}
function fuelTable(){const items=state.fuel.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||''));return table(['Data','Posto','Litros','Valor/L','Total','Odômetro','Km rodados','Km/L','Custo/Km',''],items.map((f,i)=>{const c=fuelCalc(f,i);return `<tr><td>${dateBR(f.date)}</td><td>${f.station||'—'}</td><td>${num(f.liters)}</td><td>${money(f.pricePerLiter)}</td><td>${money(c.total)}</td><td>${num(f.odometer)}</td><td>${num(c.km)}</td><td>${num(c.kml)}</td><td>${money(c.costKm)}</td><td>${delBtn('fuel',f.id)}</td></tr>`}))}
function cashTable(){let balance=0;const arr=state.cashflow.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||''));return table(['Data','Descrição','Entrada','Saída','Saldo',''],arr.map(x=>{balance+=Number(x.income||0)-Number(x.expense||0);return `<tr><td>${dateBR(x.date)}</td><td>${x.description||'—'}</td><td>${money(x.income)}</td><td>${money(x.expense)}</td><td class="${balance>=0?'positive':'negative'}">${money(balance)}</td><td>${delBtn('cashflow',x.id)}</td></tr>`}))}
function clientTable(){return table(['Empresa/Cliente','Contato','Telefone','E-mail','Cidade','Observações',''],state.clients.map(x=>`<tr><td>${x.company||'—'}</td><td>${x.contact||'—'}</td><td>${x.phone||'—'}</td><td>${x.email||'—'}</td><td>${x.city||'—'}</td><td>${x.notes||'—'}</td><td>${delBtn('clients',x.id)}</td></tr>`))}
function maintenanceTable(){return table(['Data','Serviço','Fornecedor','Valor','Próxima revisão',''],state.maintenance.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(x=>`<tr><td>${dateBR(x.date)}</td><td>${x.service||'—'}</td><td>${x.vendor||'—'}</td><td>${money(x.value)}</td><td>${x.next||'—'}</td><td>${delBtn('maintenance',x.id)}</td></tr>`))}
function installmentTable(){return table(['Parcela','Vencimento','Valor','Status',''],state.installments.slice().sort((a,b)=>Number(a.number)-Number(b.number)).map(x=>`<tr><td>${x.number||'—'}</td><td>${dateBR(x.dueDate)}</td><td>${money(x.value)}</td><td><span class="pill ${x.paid?'':'warn'}">${x.paid?'Pago':'Pendente'}</span></td><td>${delBtn('installments',x.id)}</td></tr>`))}
function agendaTable(){return table(['Data','Compromisso','Responsável','Status',''],state.agenda.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||'')).map(x=>`<tr><td>${dateBR(x.date)}</td><td>${x.task||'—'}</td><td>${x.owner||'—'}</td><td><span class="pill ${x.status==='Concluído'?'':'warn'}">${x.status||'Pendente'}</span></td><td>${delBtn('agenda',x.id)}</td></tr>`))}
const forms={
 addFreight:{title:'Registrar frete',target:'freights',fields:[['date','Data','date',today()],['driver','Motorista','text',()=>state.settings.driver],['app','App/Empresa','select',APPS],['ref','ID Frete/Corrida','text'],['client','Cliente/Descrição','text'],['origin','Origem','text'],['destination','Destino','text'],['kmInitial','Km inicial','number'],['kmFinal','Km final','number'],['gross','Valor bruto','number'],['toll','Pedágio','number'],['otherCosts','Outros custos','number'],['status','Status','select',['Concluído','Em andamento','Cancelado']],['notes','Observação','textarea']]},
 addToll:{title:'Registrar pedágio',target:'tolls',fields:[['date','Data','date',today()],['app','App/Empresa','select',APPS],['ref','ID Frete/Corrida','text'],['plaza','Praça/Concessionária','text'],['route','Trecho','text'],['value','Valor do pedágio','number'],['payment','Forma de pagamento','select',['TAG','PIX','Dinheiro','Cartão','Outro']],['reimbursable','Reembolsável?','select',['Sim','Não']],['reimbursed','Valor reembolsado','number'],['notes','Observação','textarea']]},
 addReceivable:{title:'Registrar recebível',target:'receivables',fields:[['serviceDate','Data do serviço','date',today()],['dueDate','Vencimento','date'],['app','App/Empresa','select',APPS],['ref','ID Frete/Corrida','text'],['description','Descrição','text'],['gross','Valor bruto','number'],['fees','Taxas/Descontos','number'],['status','Status','select',['Pendente','Programado','Recebido','Atrasado','Contestação','Cancelado']],['receivedDate','Data recebimento','date'],['received','Valor recebido','number'],['notes','Observação','textarea']]},
 addFuel:{title:'Registrar abastecimento',target:'fuel',fields:[['date','Data','date',today()],['station','Posto','text'],['liters','Litros','number'],['pricePerLiter','Valor por litro','number'],['odometer','Km atual / odômetro','number'],['notes','Observação','textarea']]},
 addCash:{title:'Movimento de caixa',target:'cashflow',fields:[['date','Data','date',today()],['description','Descrição','text'],['income','Entrada','number'],['expense','Saída','number']]},
 addClient:{title:'Cadastrar cliente',target:'clients',fields:[['company','Empresa/Cliente','text'],['contact','Contato','text'],['phone','Telefone','tel'],['email','E-mail','email'],['city','Cidade','text'],['notes','Observações','textarea']]},
 addMaintenance:{title:'Registrar manutenção',target:'maintenance',fields:[['date','Data','date',today()],['service','Serviço','text'],['vendor','Fornecedor','text'],['value','Valor','number'],['next','Próxima revisão','text']]},
 addInstallment:{title:'Registrar parcela da Strada',target:'installments',fields:[['number','Número da parcela','number'],['dueDate','Vencimento','date'],['value','Valor','number','2000'],['paid','Pago?','select',[['false','Não'],['true','Sim']]]]},
 addAgenda:{title:'Novo compromisso',target:'agenda',fields:[['date','Data','date',today()],['task','Compromisso','text'],['owner','Responsável','text',()=>state.settings.driver],['status','Status','select',['Pendente','Em andamento','Concluído']]]}
};
function fieldHTML([name,label,type,def]){let d=typeof def==='function'?def():def;if(type==='select'){const opts=Array.isArray(d)?d:[];return `<div class="field"><label>${label}</label><select name="${name}">${opts.map(o=>Array.isArray(o)?`<option value="${o[0]}">${o[1]}</option>`:`<option value="${o}">${o}</option>`).join('')}</select></div>`}if(type==='textarea')return `<div class="field full"><label>${label}</label><textarea name="${name}"></textarea></div>`;return `<div class="field"><label>${label}</label><input name="${name}" type="${type}" step="${type==='number'?'0.01':'any'}" value="${d??''}"></div>`}
function openForm(action){const f=forms[action];if(!f)return;$('#modalTitle').textContent=f.title;const form=$('#modalForm');form.innerHTML=f.fields.map(fieldHTML).join('')+`<div class="form-actions"><button type="button" class="btn ghost" data-close>Cancelar</button><button class="btn" type="submit">Salvar</button></div>`;$('#modalBackdrop').hidden=false;form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());for(const k of Object.keys(data)){if(['number'].includes(form.elements[k]?.type))data[k]=Number(data[k]||0)}if('paid'in data)data.paid=data.paid==='true';state[f.target].push({id:uid(),...data});$('#modalBackdrop').hidden=true;save()};form.querySelector('[data-close]').onclick=closeModal}
function closeModal(){$('#modalBackdrop').hidden=true}
function bindPage(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>handleAction(b.dataset.action));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const [type,id]=b.dataset.delete.split(':');if(confirm('Excluir este registro?')){state[type]=state[type].filter(x=>x.id!==id);save()}});const sf=$('#settingsForm');if(sf)sf.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(sf).entries());state.settings={...state.settings,costPerKm:Number(d.costPerKm||0),fixedCosts:Number(d.fixedCosts||0),monthlyTarget:Number(d.monthlyTarget||0),profitTarget:Number(d.profitTarget||0),vehicle:d.vehicle,driver:d.driver};save()}}
function handleAction(a){if(forms[a])return openForm(a);if(a==='exportData'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`ge-alianca-backup-${today()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}if(a==='importData')$('#importInput').click();if(a==='resetData'&&confirm('Apagar todos os dados deste dispositivo?')){state=structuredClone(defaultState);save()}}
$('#importInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);state={...structuredClone(defaultState),...imported};save();toast('Backup importado')}catch{alert('Arquivo de backup inválido')}};reader.readAsText(file);e.target.value=''};
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target===e.currentTarget)closeModal()};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
